
version: "3.8"
services:

  sql-server-db:
    container_name: cqrs-sql-server-db
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "local_sql_server_db_123!"
      ACCEPT_EULA: "Y"

#  cqrsapi:
#    image: cqrsapi
#    build:
#      context: .
#      dockerfile: CQRSApi/Dockerfile
